sudo: required
services:
  - docker
before_install:
  - docker build -t yash028/frontend -f Dockerfile.dev .
script:
  - docker run -it yash028/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2" 
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket-name: "elasticbeanstalk-us-east-2-169640583188"
  bucket-path: "docker-frontend"
  access_key_id: $AWS-access-key
  secret_access_key:
    secure: $AWS-secret-access-key
  on:
    branch: master